### ISSUE TITLE
Compatibility with Xmonad

### ISSUE THREAD

**Issue by errare-humanum-est1** [mendhak/grub-reboot-picker#2]
I know you mentioned that you only tested on Ubuntu, but if you're interested in making it compatible with arch, the only problem right now is that the menu executes the commands when hovering over the entry, not when clicking.
I am on the newest kernel (5.17.5) and python 3.10, im using xmonad, as window manager, and xmonbar with trayer

EDIT: kernel version and window manager information

**Comment by mendhak** [comment]
At last I was able to get tray icons working.  I had to install https://extensions.gnome.org/extension/615/appindicator-support/ and also https://flathub.org/apps/details/org.gnome.Extensions and then turn on the Extensions.  

However, the behaviour you mentioned, I didn't see that.  The system only reboots when I click on a menu item.  

![image](https://user-images.githubusercontent.com/746276/168391496-f8ef513d-9911-4a39-ad79-2ed550812718.png)

Now I don't really understand xmonad and xmobar, but I installed them using `sudo pacman -S xmonad xmobar` and then I logged out, chose xmonad from the login screen, but when I login, the screen is just blank.  I have no idea what is happening here.

**Comment by tim-py399** [comment]
I apologize for the disrespectful amount of time I haven't come back here.

so xmonad is a tiling window manager that relies on a user-created config file.
What you experienced was

**Comment by tim-py399** [comment]
![grub-reboot-picker](https://user-images.githubusercontent.com/76850480/173820920-9a5138d1-b1ed-48ec-bc16-961475d03bf4.png)

I apologize for responding late to this topic.

You would install the package from the AUR using some AUR-Helper like yay. 

Xmonad is a tiling window manager that relies on a user-edited config file. What you experienced was the default behaviour, pressing Alt + Shift + Enter will bring up a terminal. 

I have some new Information about the behaviour I'm experiencing.
1. I have tested it in GNOME, and i can confirm that the issue is not with Arch itself, but the windowmanager xmonad. (I changed the Issue name accordingly) 
2. In the provided picture you can see that the reboot picker interprets the actual bootable Entrys as folders, but the only folder should be the Advanced Options.
3. There is a Critical error you can see in the Terminal Emulator, i have no clue what it means as I have no clue of GDK-Programming or UI programms in general, maybe that can help you.

**Comment by mendhak** [comment]
@errare-humanum-est1 while testing on Ubuntu 24.04 I was able to reproduce the "activate on mouse hover" issue. I do have a workaround for it here. At some point this should make its way to the next release. 

https://github.com/mendhak/grub-reboot-picker/pull/7/files#diff-ec1a1686f710546e40a3ab11f7684e7c7720a631feab4204bed44d194e121868R136-R145

**Comment by mendhak** [comment]
OK so a new version 0.0.9 is published and that activate-on-hover problem should go away, at least the specific one I found should go away.
